service: users-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    USERS_TABLE: users
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/370081004539/users-create-queue
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:370081004539:user-created-notification-topic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/users
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:us-east-1:370081004539:users-create-queue
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - arn:aws:sns:us-east-1:370081004539:user-created-notification-topic
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:GetQueueUrl
      Resource:
        - arn:aws:sqs:us-east-1:370081004539:users-create-queue

functions:
  getUsers:
    handler: nodejs/handlers/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: GET

  createUser:
    handler: nodejs/handlers/createUser.createUser
    events:
      - httpApi:
          path: /users
          method: POST

  updateUser:
    handler: com.users.handlers.UpdateUserHandler::handleRequest
    runtime: java17
    package:
      artifact: java/target/java-handlers-1.0-SNAPSHOT.jar
    events:
      - httpApi:
          path: /users/{id}
          method: PUT

  deleteUser:
    handler: com.users.handlers.DeleteUserHandler::handleRequest
    runtime: java17
    package:
      artifact: java/target/java-handlers-1.0-SNAPSHOT.jar
    events:
      - httpApi:
          path: /users/{id}
          method: DELETE

  sendEmails:
    handler: nodejs/handlers/sendEmails.sendEmails
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:370081004539:users-create-queue
          batchSize: 1

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
