plugins {
    id 'java'
}

group 'com.users'
version '1.0-SNAPSHOT'

sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.2'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}

jar {
    archiveBaseName.set("java-handlers")         
    destinationDirectory.set(file("$projectDir/target")) 
    manifest {
        attributes 'Main-Class': 'com.users.handlers.UpdateUserHandler' 
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
